# Generated by Django 4.2.30 on 2026-05-11 11:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Government Administrator'), ('BUSINESS', 'Business / Contractor'), ('JOURNALIST', 'Journalist / Public')], help_text='User role in the system', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False, help_text='Email confirmed (FR_08)')),
                ('is_suspended', models.BooleanField(default=False, help_text='Account suspended by admin (FR_35)')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, help_text='Number of failed login attempts (FR_09)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('registration_no', models.CharField(help_text='Business registration number (NIPT)', max_length=100, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('iso_certificate', models.FileField(blank=True, help_text='ISO 14001 or other environmental certificate', upload_to='certificates/iso/')),
                ('qkb_document', models.FileField(blank=True, help_text='QKB document (National Business Centre)', upload_to='certificates/qkb/')),
                ('eco_score', models.FloatField(default=0.0, help_text='Environmental score 0-100, calculated automatically (FR_41)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_verified', models.BooleanField(default=False, help_text='Profile verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(help_text='The Business user linked to this profile', limit_choices_to={'role': 'BUSINESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='EcoMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(choices=[('PHOTO', 'Geotagged Photo'), ('DOCUMENT', 'Legal Document (PDF)'), ('BOTH', 'Photo and Document'), ('REPORT', 'Technical Report')], help_text='Type of evidence required from the business', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted (Under Review)'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OVERDUE', 'Overdue'), ('ACTION_REQUIRED', 'Action Required'), ('EXTENSION_PENDING', 'Extension Request Pending')], default='PENDING', max_length=25)),
                ('deadline', models.DateTimeField(help_text='Deadline for submitting evidence')),
                ('weight', models.PositiveSmallIntegerField(default=10, help_text='Weight for Eco-Score calculation — all weights should sum to 100')),
                ('review_comment', models.TextField(blank=True, help_text='Admin comment during approval / rejection')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eco-Milestone',
                'verbose_name_plural': 'Eco-Milestones',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS coordinate - latitude (FR_11)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS coordinate - longitude (FR_11)', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open (Accepting Applications)'), ('REVIEW', 'Under Review'), ('EXECUTION', 'In Execution'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low    (Green)'), ('MEDIUM', 'Medium (Orange)'), ('HIGH', 'High   (Red)')], default='MEDIUM', max_length=10)),
                ('submission_deadline', models.DateTimeField(help_text='Deadline for submitting applications')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('has_red_flag', models.BooleanField(default=False, help_text='True when a journalist submits a discrepancy report (UC-16)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.PROTECT, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('winning_business', models.ForeignKey(blank=True, help_text='Winning business after UC-07', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_projects', to='greentrace.companyprofile')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_deadline', models.DateTimeField(help_text='New proposed deadline submitted by the business')),
                ('justification', models.TextField(help_text='Business justification for the extension request')),
                ('justification_doc', models.FileField(blank=True, help_text='Supporting document (e.g. weather report, invoice)', upload_to='extensions/docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('admin_comment', models.TextField(blank=True, help_text='Admin comment during approval or rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='greentrace.ecomilestone')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extensions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Extension Request',
                'verbose_name_plural': 'Extension Requests',
            },
        ),
        migrations.AddField(
            model_name='ecomilestone',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='greentrace.project'),
        ),
        migrations.AddField(
            model_name='ecomilestone',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DiscrepancyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=False, help_text="If True, the reporter's identity is kept confidential")),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Description of the violations observed on site')),
                ('evidence_file', models.FileField(blank=True, help_text='Photo or video evidence uploaded by the reporter', upload_to='reports/evidence/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('admin_response', models.TextField(blank=True, help_text='Official admin response to the report')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_reports', to='greentrace.project')),
                ('reported_by', models.ForeignKey(blank=True, help_text='NULL when the report is anonymous (is_anonymous=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discrepancy Report',
                'verbose_name_plural': 'Discrepancy Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PHOTO', 'Geotagged Photo'), ('DOCUMENT', 'Legal Document (PDF)')], max_length=20)),
                ('file', models.FileField(help_text='Photo (jpg/png) or document (pdf)', upload_to='evidence/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude from photo EXIF data', max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude from photo EXIF data', max_digits=9, null=True)),
                ('captured_at', models.DateTimeField(blank=True, help_text='Original timestamp from photo EXIF data', null=True)),
                ('gps_validated', models.BooleanField(default=False, help_text='True if coordinates match the project site location')),
                ('validity_date', models.DateField(blank=True, help_text='Expiry date of the legal document', null=True)),
                ('document_type', models.CharField(blank=True, help_text='e.g. Waste Permit, Water Test, Transport Permit', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='greentrace.ecomilestone')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Evidence',
                'verbose_name_plural': 'Compliance Evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Short description of the action (e.g. 'Milestone APPROVED')", max_length=255)),
                ('model_name', models.CharField(help_text="Affected Django class (e.g. 'EcoMilestone')", max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the changed object', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details such as before/after values')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='HTTP client IP at the time of the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='NULL if the action is system-generated (automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TenderApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('SHORTLISTED', 'Shortlisted'), ('APPROVED', 'Approved / Winner'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('technical_proposal', models.FileField(help_text='Business technical proposal (PDF)', upload_to='applications/technical/')),
                ('env_impact_statement', models.FileField(help_text='Environmental Impact Statement (PDF)', upload_to='applications/env_impact/')),
                ('financial_bid', models.DecimalField(decimal_places=2, help_text='Financial bid amount', max_digits=15)),
                ('admin_score', models.FloatField(blank=True, help_text='Score assigned by admin after UC-07', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection by admin')),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Timestamp of final submission', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='greentrace.companyprofile')),
                ('evaluated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='greentrace.project')),
            ],
            options={
                'verbose_name': 'Tender Application',
                'verbose_name_plural': 'Tender Applications',
                'unique_together': {('project', 'business')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('REALTIME', 'Real-time'), ('WEEKLY', 'Weekly')], default='REALTIME', max_length=10)),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='greentrace.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Follow',
                'verbose_name_plural': 'Project Follows',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='CarbonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveSmallIntegerField(help_text='Reporting month (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('period_year', models.PositiveIntegerField(help_text='Reporting year (e.g. 2025)')),
                ('fuel_liters', models.FloatField(default=0.0, help_text='Litres of fuel consumed during this month')),
                ('electricity_kwh', models.FloatField(default=0.0, help_text='Kilowatt-hours of electricity consumed')),
                ('total_co2_kg', models.FloatField(blank=True, help_text='Total CO2 (kg) - calculated automatically', null=True)),
                ('exceeds_limit', models.BooleanField(default=False, help_text='True if project carbon limit is exceeded (FR_42)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_records', to='greentrace.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carbon_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carbon Data',
                'verbose_name_plural': 'Carbon Data',
                'unique_together': {('project', 'period_month', 'period_year')},
            },
        ),
    ]
